force_sub: true
web: true

pyrogram:
  plugin_dir: "bot/plugins"
  test_mode: false
  in_memory_session: false
  
commands:
   prefix: ["/", "."]
   case_sensitive: false
   
translation:
   dir: "bot/translation"
   default_language: "en"
   
logging:
    loggers:
        root:
          level: "INFO"      #{'CRITICAL': 50, 'FATAL': 50, 'ERROR': 40, 'WARN': 30, 'WARNING': 30, 'INFO': 20, 'DEBUG': 10, 'NOTSET': 0}
          handlers: ["telegram", "file"]
        tgbot:
          level: "INFO"
        pyrogram:
          level: "WARNING"
        pyrogram.parser.html:
          level: "ERROR"
        pyrogram.session.session:
          level: "ERROR"
    handlers:
      telegram:
        chat: -1002233681213
        thread: 2
        chunk: 4000
      file:
        path: "logs/bot.log"
        maxSize: "1 MB" 
        backupCount: 5
    
FORCE_SUB_CHANNEL: "@theostrich"


user_check:
  force_sub: false
  accept_tc: true
  ban: true

groups:
  admin: [1775541139, 1520625615, 1809735866]
  tester: [ 2023698054 ]

subscriptions:
  - name: "free"
    data:
      limits:
        max_mails: 3  
  - name: "premium"
    data:
      prices: 
        - price: "100,xtr"
          validity: "1,month"
        - price: "200,xtr"
          validity: "3,month"

      limits:
        max_mails: 7
        custom_domains: true
        send: true

broadcast:
  users: all    #no. of users to send the message to
  mode: forward #available options: forward, copy


MongoDB:
  database: tesseract

links:
  channel_url: "t.me/theostrich"
  group_url  : "t.me/ostrichdiscussion"
  donation_url: "https://paypal.me/donateostrich"
  repo_url: "https://github.com/RabbitFored/mailable"

extras:
  domains: ['mail.bruva.co', '4qnt.us']
  reserved_keyword : [
    'admin', 'owner', 'contact', 'support', 'donate', 'postmaster', 'message',
    'ostrich', 'administrator', 'access', 'account', 'mail', 'email', 'patner',
    'admins', 'porn', 'gov', 'government', 'noreply', 'subscribe', 'free',
    'paid', 'api', 'auth', 'dev', 'developers', 'docs', 'faq', 'group',
    'groups', 'help', 'hostmaster', 'join', 'local', 'login', 'master',
    'register', 'root', 'terms', 'user', 'webmaster', 'quantum', 'theostrich',
    'chat', 'melvik', 'storm', 'melvikstorm'
]

