app_name: tgbot
app_version: 1.0.0

pyrogram:
  plugin_dir: "bot/plugins"
  #alt_port: true 
  #use_mongodb_for_session: true
  #if true, port 5222 will be used to connect to Telegram.
  #  test_mode: false            #connect to test servers 
  #  use_ipv6: false
  #  in_memory_session: false    #defaults to true when using session_string
  #  proxy:
  #    scheme: socks5   # "socks4", "socks5" and "http" are supported
  #    hostname: 11.22.33.44
  #    port: 1234

plugins:
   load_modules: true
   dir: "bot/plugins"
   repo:
     - "https://github.com/RabbitFored/telegram-bot-plugins.git"
   include: ['admin', 'misc', 'subscription']
   exclude: []
    
commands:
   prefix: ["/", "."]
   case_sensitive: false
   
translation:
   dir: "bot/translation"
   default_language: "en"
   use_from_env: true

logging:
    loggers:
        root:
          level: "INFO"
          handlers: ["telegram", "file"]
        tgbot:
          level: "INFO"
        pyrogram:
          level: "WARNING"
        pyrogram.parser.html, pyrogram.session.session:
          level: "ERROR"
    handlers:
      telegram:
        level: "INFO"
        chat: -1002233681213
        thread: 2
        chunk: 4000
      file:
        level: "DEBUG"
        path: "logs/bot.log"
        maxSize: "1 MB" 
        backupCount: 5

groups:
  admin: [1775541139, 1520625615, 1809735866]
  tester: [ 2023698054 ]

subscriptions:
- name: "free"
  data:
    limits:
      max_mails: 3  
- name: "premium"
  data:
    prices: 
      - price: "100,xtr"
        validity: "1,month"
      - price: "200,xtr"
        validity: "3,month"
    limits:
        max_mails: 7
        custom_domains: true
        send: true
      
filters:
  accept_tc: true
  ban: true
  force_sub:
      chats: 
         - "@theostrich"
#  antiflood:
#      message_interval: 5
#      message_count: 5
  disallow: #restrict these users from accessing bot
     users: []
     groups: []
  exclude: #dont check for these users
     groups: ["admin"]
     subscriptions: ["premium"]

broadcast:
  users: all    #no. of users to send the message to
  mode: forward #available options: forward, copy

links:
  channel_url: "t.me/theostrich"
  group_url  : "t.me/ostrichdiscussion"
  donation_url: "https://paypal.me/donateostrich"
  repo_url: "https://github.com/RabbitFored/mailable"

extras:
  domains: ['mail.bruva.co', '4qnt.us']
  reserved_keyword : [
    'admin', 'owner', 'contact', 'support', 'donate', 'postmaster', 'message',
    'ostrich', 'administrator', 'access', 'account', 'mail', 'email', 'patner',
    'admins', 'porn', 'gov', 'government', 'noreply', 'subscribe', 'free',
    'paid', 'api', 'auth', 'dev', 'developers', 'docs', 'faq', 'group',
    'groups', 'help', 'hostmaster', 'join', 'local', 'login', 'master',
    'register', 'root', 'terms', 'user', 'webmaster', 'quantum', 'theostrich',
    'chat', 'melvik', 'storm', 'melvikstorm'
]
